mybatis 세팅
f-lab-edu/foody-lab pull request #35
Opened 2022-10-27 12:25 UTC by Taewoongjung

### 이슈
[28] mybatis 세팅

### 작업사항
* mybatis 세팅
* 3306 포트에서 3308 포트로 포트포워딩 하였습니다. 기본 포트가 datagrip에 물리지 않기 때문이었습니다.

### 테스트 사항
* mybatis와 mysql 연동 테스트

2022-10-27 12:43 UTC, Bue-von-hon requested changes

2022-10-27 12:43 UTC, Bue-von-hon commented on src/main/java/app/foodylab/store/Store.java
> +    private final String name;
name이 Order클래스 생성할때 쓰였던 storeId인가요?
같은거면 storeId로 통일해야 할것 같아서요

2022-10-27 12:43 UTC, Bue-von-hon commented on src/main/java/app/foodylab/store/StoreState.java
> +    CLOSED("N");
Y, N 대신 의미를 알 수 있으면 좋을것 같네요

2022-10-27 12:43 UTC, Bue-von-hon commented on src/main/java/app/foodylab/user/adapter/infra/mybatis/UserMybatisRepository.java
> +@Service
클래스 이름은 레포지토리인데 서비스 어노테이션이 붙어있네요?!

2022-10-27 12:43 UTC, Bue-von-hon commented on src/main/java/app/foodylab/user/adapter/infra/mybatis/UserMybatisRepository.java
> +package app.foodylab.user.adapter.infra.mybatis;
패키지를 이렇게 나눈 이유가 궁금해요..!
어뎁터와 인프라 사이에 다른게 있을수 있나요?🤔🤔

2022-10-27 12:49 UTC, Taewoongjung commented on src/main/java/app/foodylab/user/adapter/infra/mybatis/UserMybatisRepository.java
> +@Service
아 그렇네요!

2022-10-27 13:01 UTC, Taewoongjung commented on src/main/java/app/foodylab/store/Store.java
> +    private final String name;
name은 가게의 이름을 뜻합니다. (상호명 입니다.)

2022-10-27 13:09 UTC, Bue-von-hon commented on src/main/java/app/foodylab/user/adapter/infra/mybatis/UserMybatisRepository.java
> +package app.foodylab.user.adapter.infra.mybatis;
jpa랑 mybatis 전부 쓰는 상황을 염두해두셨다는 말씀이시군요👍

2022-10-27 13:48 UTC, Taewoongjung commented
@f-lab-Carrey 이 티켓 끝나는대로 바로 h2랑 flyway 세팅된 것 올리겠습니다! (원래 h2랑 flyway는 각각 티켓이 발행되어 있었는데 h2랑 flyway의 init 데이터가 resources 폴더에서 충돌이 나는 이슈가 있어서 같이 했습니다.)

2022-10-27 15:17 UTC, f-lab-Carrey commented on src/main/resources/docker/docker-compose.yml
>        MYSQL_USER: sample_user
docker-compose.yml은 프로젝트 루트에 빼두는게 아마 실행하기 편하실 것 같네요~

2022-10-27 15:17 UTC, f-lab-Carrey commented on src/main/java/app/foodylab/store/Store.java
> +    private final String name;
도메인 클래스에서도 storeId에 대한 값이 필요할 것 같네요~ 다시 한번 검토 부탁드립니다~!

2022-10-27 15:17 UTC, f-lab-Carrey commented on src/main/java/app/foodylab/store/Store.java
> +    private final long minimumOrderAmount;
amount와 price 용어를 한번 정리하면 좋을 것 같아요~

2022-10-27 15:17 UTC, f-lab-Carrey commented on src/main/java/app/foodylab/store/StoreState.java
> +    public String getValue() {
얘도 lombok을 사용하도록 연습해보면 좋겠습니다🥸

2022-10-27 15:17 UTC, f-lab-Carrey commented on src/main/java/app/foodylab/store/StoreState.java
> +    StoreState(String value) {
생성자도 마찬가지로 lombok을 사용해보면 좋겠습니다🥸

2022-10-27 15:17 UTC, f-lab-Carrey commented on src/main/resources/docker/docker-compose.yml
> +      - "3308:3306"
저는 3306 포트로도 접근이 잘되는 것 같긴합니다~
하지만 기본 포트를 노출하지 않는 것은 보안상 아주 좋은 패턴이기 때문에 추천합니다~

2022-10-27 15:17 UTC, f-lab-Carrey commented on src/main/resources/mybatis/mapper/UserDao.xml
> +      (#{user.id}, #{user.name});
mybatis에는 ${} 와 #{} 로 매개변수를 넘길 수 있습니다.
이 두개의 차이점에 대해서는 숙지 부탁드리겠습니다~

2022-10-27 15:18 UTC, f-lab-Carrey commented on src/main/java/app/foodylab/store/Store.java
> +package app.foodylab.store;
여기도 패키지 구조를 user와 통일해보면 좋겠네요~!

2022-10-27 15:19 UTC, f-lab-Carrey commented on src/main/java/app/foodylab/store/StoreState.java
> +    StoreState(String value) {
생성자 Access Level에 대해서도 고민 부탁드립니다~

2022-10-27 15:20 UTC, f-lab-Carrey commented on src/main/java/app/foodylab/user/application/dao/UserDao.java
> +import org.apache.ibatis.annotations.Param;
mybatis 기술에 의존하고 있습니다. 해당 클래스의 패키지에 대해 다시 검토 부탁드립니다~

2022-10-28 00:20 UTC, Bue-von-hon commented on src/main/java/app/foodylab/store/Store.java
> +    private final long minimumOrderAmount;
수정했습니다~!
[커밋](https://github.com/f-lab-edu/foody-lab/pull/35/commits/b1863810dd4772bdbc0a7b75225c3e37eab6ca7a)

2022-10-28 00:31 UTC, f-lab-Carrey commented on src/main/java/app/foodylab/store/Store.java
> +    private final long minimumOrderAmount;
이 PR은 태웅님이 올리신 PR이라 수정에 대한 모든 것은 태웅님이 직접 해주시면 좋을 것 같아요~ 오너십이 태웅님에게 있다고 생각해서요

2022-10-28 00:33 UTC, Bue-von-hon commented on src/main/java/app/foodylab/store/Store.java
> +    private final long minimumOrderAmount;
> 이 PR은 태웅님이 올리신 PR이라 수정에 대한 모든 것은 태웅님이 직접 해주시면 좋을 것 같아요~ 오너십이 태웅님에게 있다고 생각해서요

앗..! 죄송합니다! 의욕이 과했네요!!🙇🏻‍♂️🙇🏻‍♂️

2022-10-28 02:49 UTC, Taewoongjung commented on src/main/resources/mybatis/mapper/UserDao.xml
> +      (#{user.id}, #{user.name});
AUTO_INCREMENT 방식 사용합니다.

2022-10-28 03:04 UTC, Taewoongjung commented on src/test/java/app/foodylab/user/service/UserServiceTest.java
> +    private final UserMybatisRepository userRepository = mock(UserMybatisRepository.class);
네 인지하고 있었습니다. 마일스톤 phase3이 끝나고 헥사고널 구조로(adaptor, application, domain) 변경 후 이런식으로 변경할 예정이었습니다. 
<img width="483" alt="image" src="https://user-images.githubusercontent.com/70272679/198486674-e1216274-f896-43ea-bc0d-500ba4ebb0e0.png">

굳이 나중에 가서 바꿀 필요는 없겠네요. 지금 바꾸겠습니다!

2022-10-28 03:06 UTC, Taewoongjung commented on src/main/resources/docker/docker-compose.yml
>        MYSQL_USER: sample_user
맞아요 해당 경로에 가서 명령어 실행을 해야하더라고요 ~

2022-10-28 03:41 UTC, f-lab-Carrey commented
> @f-lab-Carrey 이 티켓 끝나는대로 바로 h2랑 flyway 세팅된 것 올리겠습니다! (원래 h2랑 flyway는 각각 티켓이 발행되어 있었는데 h2랑 flyway의 init 데이터가 resources 폴더에서 충돌이 나는 이슈가 있어서 같이 했습니다.)

어차피 같은 sql 파일인데 이를 같이 활용할 수 있는 방법이 있을 수 있을 것 같아요~ 한번 고민부탁드려요~

2022-10-28 03:45 UTC, f-lab-Carrey commented on src/main/resources/mybatis/mapper/UserDao.xml
> +      (#{user.id}, #{user.name});
mybatis의 경우에는 User 객체를 저장 후에 id 값을 바로 알 수 있나요~?

2022-10-28 03:56 UTC, Taewoongjung commented on src/main/resources/mybatis/mapper/UserDao.xml
> +      (#{user.id}, #{user.name});
모릅니다! 태훈님 PR에서 나온거 그대로 했는데 태훈님이 수정하신거라 원래 그대로 옮겨놓았습니다. 
@Bue-von-hon 제가 수정해도 될까요?

2022-10-28 03:58 UTC, Taewoongjung commented on src/main/resources/mybatis/mapper/UserDao.xml
> +      (#{user.id}, #{user.name});
저 때 제가 User 객체 간단히 만들 때 id를 로그인할 때 id로 만들어 놓았었네요..ㅋㅋ

2022-10-28 04:17 UTC, Bue-von-hon commented on src/main/resources/mybatis/mapper/UserDao.xml
> +      (#{user.id}, #{user.name});
무슨 말씀이신지 이해했습니다.
JPA의 경우 insert날리면 바로 id를 가져올 수 있는데(먼저번에 학습한대로 select를 알게모르게 날리는 거지만..ㅋㅋ)
마이바티스의 경우에는 다를 수 있다는 말씀이시지요?
요거는 실제로 동작과정을 한번 살펴보겠습니다 금방 끝나니까요~!😎😎

2022-10-28 04:21 UTC, Taewoongjung commented on src/main/resources/mybatis/mapper/UserDao.xml
> +      (#{user.id}, #{user.name});
오 JPA에는 그런 기능이 있었군요!

2022-10-28 05:47 UTC, Taewoongjung commented
@f-lab-Carrey @Bue-von-hon 말씀해주신점 고쳐보았습니다🙏🏻

2022-10-28 05:48 UTC, Bue-von-hon commented on src/main/java/app/foodylab/adaptor/controller/UserController.java
> +import app.foodylab.domain.user.User;
이거는 제 PR 머지되면 수정될 부분입니다!
DTO를 새로 만들었거든요!
(이대로 두셔도 괜찮다는 의미!!🐼🐼)

2022-10-28 05:50 UTC, Bue-von-hon commented on src/main/java/app/foodylab/adaptor/infra/mybatis/repository/user/UserMybatisRepository.java
> +@Service
이거는 @Repository를 붙혀야 할 것 같아요!

2022-10-28 05:51 UTC, Bue-von-hon commented on src/main/java/app/foodylab/adaptor/infra/mybatis/repository/user/UserMybatisRepository.java
> +package app.foodylab.adaptor.infra.mybatis.repository.user;
여기가 매퍼 모으신다고 했던 그 부분인가요?

2022-10-28 05:52 UTC, Taewoongjung commented on src/main/java/app/foodylab/adaptor/infra/mybatis/repository/user/UserMybatisRepository.java
> +package app.foodylab.adaptor.infra.mybatis.repository.user;
app.foodylab.adaptor.mapper 이 경로에 모아놓았습니다.

2022-10-28 05:53 UTC, Bue-von-hon commented on src/main/java/app/foodylab/application/user/dto/UserDTO.java
> +}
헉..! 이 친구는 제가 PR보낸 클래스랑 전부 겹치네요!!
오브젝트 매핑 라이브러리 도입하면서 DTO를 만들었는데..!

2022-10-28 05:54 UTC, Taewoongjung commented
> > @f-lab-Carrey 이 티켓 끝나는대로 바로 h2랑 flyway 세팅된 것 올리겠습니다! (원래 h2랑 flyway는 각각 티켓이 발행되어 있었는데 h2랑 flyway의 init 데이터가 resources 폴더에서 충돌이 나는 이슈가 있어서 같이 했습니다.)
> 
> 어차피 같은 sql 파일인데 이를 같이 활용할 수 있는 방법이 있을 수 있을 것 같아요~ 한번 고민부탁드려요~

H2가 ansi 표준을 지원한다고 하니 사용하면 되겠네요!

2022-10-28 05:55 UTC, Taewoongjung commented on src/main/java/app/foodylab/application/user/dto/UserDTO.java
> +}
아 저 부분은 지우겠습니다!

2022-10-28 05:57 UTC, Bue-von-hon commented on src/main/java/app/foodylab/application/user/service/UserService.java
> +package app.foodylab.application.user.service;
먼가 그동안 애그리거트별로 나눠둔걸 전부 합치신것 같은데...
나중에 모듈 나눠야할때 힘들것 같아요

2022-10-28 05:59 UTC, Bue-von-hon commented on src/main/java/app/foodylab/domain/coupon/PriceCoupon.java
> +        }
오 요런 부분이 있었다니
한줄 리턴이라도 나누는게 저도 눈에 편하더라구요

2022-10-28 06:01 UTC, Taewoongjung commented on src/main/java/app/foodylab/application/user/service/UserService.java
> +package app.foodylab.application.user.service;
도메인으로 나눠져 있다고 생각해서 adaptor, application domain별로 나눴습니다. 제가 생각하는 어그리게잇은 도메인보다 더 작은 주제라고 생각했습니다.

2022-10-28 06:03 UTC, Taewoongjung commented on src/main/java/app/foodylab/application/user/service/UserService.java
> +package app.foodylab.application.user.service;
https://serialized.io/ddd/aggregates/ 여기 그림처럼 이해했습니다.

2022-10-28 06:10 UTC, Bue-von-hon commented on src/main/java/app/foodylab/application/user/service/UserService.java
> +package app.foodylab.application.user.service;
[여기](https://incheol-jung.gitbook.io/docs/study/ddd-start/3#undefined)를 참고해보시면 좋을 것 같아요
유저, 쿠폰, 주문으로 나누고, 그 안에서 헥사고날 아키텍쳐를 적용했던건데,(나중에 모듈별로 추출하기도 쉽게)
지금은 그냥 통으로 묶은걸로 보이거든요

2022-10-28 06:19 UTC, Taewoongjung commented on src/main/java/app/foodylab/application/user/service/UserService.java
> +    private final UserMapper userRepository;
<img width="483" alt="image" src="https://user-images.githubusercontent.com/70272679/198515857-db6cccdf-bdcd-4980-a5dd-ab85ce42bff0.png">
해당 그림처럼 UserMapper를 UserService가 직접적으로 UserMybatisRepository를 의존하지 않고 추상화에 의존하면서 DIP를 위반하지 않게 해보았습니다!

2022-10-28 06:19 UTC, Taewoongjung commented on src/main/java/app/foodylab/application/user/service/UserService.java
> +    private final UserMapper userRepository;
실제 의미상으로는 내부 비즈니스로직에서 해당 도메인의 Repository를 가지고 있는게 더 infra랑 관심사 분리가 된다고 생각하는데 어떻게 생각하시나요?

이렇게요!
<img width="483" alt="image" src="https://user-images.githubusercontent.com/70272679/198516958-ae2a27e3-ecea-4503-b8a1-64b02249eb42.png">

2022-10-28 06:21 UTC, Bue-von-hon commented on src/main/resources/mybatis/mapper/UserDao.xml
> +      (#{user.id}, #{user.name});
파라미터 값이 주입되는 방식에 차이가 있네요🔎🔎🔎
$는 넘어온 데이터가 그대로, #은 따옴표를 자동으로 찍어주구요
$는 "서버에서 넘겨줄때", #은 "외부 입력을 디비로 넘길때" 사용하는 차이가 있네요
또 $는 파싱된 쿼리문을 캐싱해서 "재사용"하기 대문에 조금 더 좋구요!!

[링크1](https://logical-code.tistory.com/25)
[링크2](https://madplay.github.io/post/difference-between-dollar-sign-and-sharp-sign-in-mybatis)

2022-10-28 06:28 UTC, Bue-von-hon commented on src/main/java/app/foodylab/application/user/service/UserService.java
> +    private final UserMapper userRepository;
주제와 상관없는것 같지만... 일단 용어가 눈에 걸리네요
저는 mapper는 매핑하는 용도로 사용중이고(DTO-VO 등), repo는 디비와 무언가를 할때 사용하고 있거든요
mapper와 repository가 혼용되는것 같아 헷갈리네요

2022-10-28 06:37 UTC, Taewoongjung commented on src/main/java/app/foodylab/application/user/service/UserService.java
> +package app.foodylab.application.user.service;
그 전의 파일 구조는 각 도메인별로 adaptor, application, domain으로 나눠져 있었고, 현재 변경된 구조는 각각 adaptor, application, domain 패키지가 각각의 도메인을 가지고 있는 구조인데 바뀌기 전이랑 의미는 달라진게 없다고 생각했습니다.

그렇기 때문에 이 프로젝트 구조에서도 에그리게잇을 충분히 나눌 수 있다고 생각합니다.

2022-10-28 06:39 UTC, Taewoongjung commented on src/main/java/app/foodylab/application/user/service/UserService.java
> +    private final UserMapper userRepository;
그렇죠? service가 mapper를 가지고 있는거는 의미가 조금 이상해지는 것 같기도 해요! 고민중이었습니다! 
mapper는 mybatis의 매퍼이기 때문에 이름은 저는 맞다고는 생각하지만 service가 mapper보다는 repository를 가지고 있는 것이 더 좋아보입니다.

2022-10-28 08:49 UTC, Bue-von-hon commented on src/main/java/app/foodylab/application/user/service/UserService.java
> +package app.foodylab.application.user.service;
흠...🤔🤔🤔
예를들어 변경해주신 구조에서 "유저"만 분리한다면 어떨까요?
어뎁터, 어플리케이션, 도메인에 흩어져있는 유저 패키지 안의 내용물을 모으고
유저라는 모듈 안에 다시 어뎁터, 어플리케이션, 도메인으로 분리해야할 것같아요

그 전의 구조에서는 그냥 유저 패키지만 떼어가면 되었지만 좀 더 복잡해진것 같네요🐰🐰
p.s. 심지어 서로 다른 도메인끼리 같은 패키지 안에 있어서 개발할때 "실수"하기 쉬워 보여요
e.g. 유저 도메인에서만 사용하는 친구인데 쿠폰에서 사용

2022-10-28 09:16 UTC, Taewoongjung commented on src/main/java/app/foodylab/application/user/service/UserService.java
> +package app.foodylab.application.user.service;
아 멀티모듈로 전환할 때 말씀하시는건가요? 그럴 때면 태훈님 말씀대로 해야겠죠. 그렇네요 멀티모듈로 쉽게 전환될 수 있는 구조였네요. 그럼 다시 바꾸겠습니다! 

그런데 그 전에 application, adaptor, domain, service 이렇게 나눠져 있었는데 service는 비즈니스 로직이니까 application 안에 들어갈 수 있지 않을까요?

2022-10-28 09:27 UTC, Bue-von-hon commented on src/main/java/app/foodylab/application/user/service/UserService.java
> +package app.foodylab.application.user.service;
서비스의 위치는 저도 너무 궁금합니다..🤔🤔
스프링에서 사용하는 서비스라는 친구도 있고, 최근에 배운 "도메인 서비스"라는 친구도 있어서...
저도 도움을 외쳐봅니다..! **도움**!!😆

2022-10-29 07:25 UTC, f-lab-Carrey commented on src/main/java/app/foodylab/application/user/service/UserService.java
> +package app.foodylab.application.user.service;
두가지 주제가 있네요 ㅎㅎ

1. 패키지의 시작은 layer일까? domain일까?
* 저는 사실 layer 파이긴 합니다. (많은 개발자들이 domain 파 이신분들도 있습니다)
* 장점
  * 각 Layer 안에서의 역할이 중요하다고 생각하여 나누는 편입니다.
  * 공통 코드를 어떤 도메인에 넣을까? 같은 고민을 안해도 됩니다.
  * domain layer 내에는 도메인에 대한 코드만 있기 때문에 그들간의 관계를 파악할 때 매우 용이합니다.
  * 멀티 모듈 구조에서도 라이브러리 의존성 분리가 굉장히 용이해집니다.
     * mybatis 모듈을 멀티 모듈로 나눈다면 그 모듈에만 mybatis 라이브러리 의존성이 있고 adapter 패키지만 있겠죠?
     * 실무에서는 같은 도메인 로직이 필요해서 domain 모듈을 나누고 api 모듈, batch 모듈 등에 dependency를 걸어서 씁니다.
     * 이것도 관점이 사람마다 다르긴 합니다 ㅎ
 * 단점
    * 태훈님 의견대로 도메인별로 뜯어낼때는 domain 기준 패키지 보다 비용이 많이 들기는 합니다.
    * 하지만 그건 domain 간 의존성 및 통신이 완벽하게 분리되어 있는 경우에만 패키지만 들고가는게 가능합니다.
    * 그게 아니라면 어차피 layer 기반 패키지와 차이는 없습니다.
    
 우리가 만드는 프로그램은 완벽하게 도메인 간의 의존성을 제거하기는 어렵다고 생각합니다.
 그렇기 때문에 도메인 간에도 의존성 방향이 있구요.

2022-10-29 07:28 UTC, f-lab-Carrey commented on src/main/java/app/foodylab/application/user/service/UserService.java
> +package app.foodylab.application.user.service;
2. 패키지 내에서는 어떤 클래스들이 들어가면 좋을까? 
보통 아래와 같이 나누는 것 같습니다
* adapter
  * api controller
  * api client (ex. resttemplate, webclient)
  * event queue publishser / consumer
  * repository (구현체)
* application - 애플리케이션 레이어의 역할은 도메인을 호출하는 역할이기에 service를 제외한 모든 도메인 관련 클래스가 domain에 해당됩니다
  * service
* domain
  * domain class
  * repository (interface)
  * domain service

2022-10-29 07:56 UTC, Taewoongjung commented on src/main/java/app/foodylab/application/user/service/UserService.java
> +package app.foodylab.application.user.service;
맞아요 layer로 나누면 공통 코드를 넣을 때 편리하더라고요..!! 
저는 처음에는 멀티모듈로 나눌 때 도메인별로 나눠야한다고 생각했었는데 너무 편협한 생각이었네요!

2022-10-29 08:17 UTC, Bue-von-hon commented on src/main/java/app/foodylab/application/user/service/UserService.java
> +package app.foodylab.application.user.service;
주문과 쿠폰을 아우르는 도메인 서비스의 위치 문제가 여기서 해결ㄷㄷㄷ

2022-10-31 05:29 UTC, Taewoongjung commented on src/main/java/app/foodylab/application/user/service/UserService.java
> +package app.foodylab.application.user.service;
프로젝트 구조를 layer로 하기로 상의 되었습니다 ~

2022-10-31 06:00 UTC, Bue-von-hon commented on src/main/java/app/foodylab/adaptor/infra/mybatis/repository/user/UserMybatisRepository.java
> +@Service
이거 아직도 레포지토리 같습니다..?😮😮

2022-10-31 07:45 UTC, f-lab-Carrey commented
혹시 위에서 논의한 내용 중 추가적인 작업이 남았는지 궁금합니다~

2022-10-31 08:39 UTC, Taewoongjung commented on src/main/java/app/foodylab/adaptor/infra/mybatis/repository/user/UserMybatisRepository.java
> +@Service
아직 바꿔놓고 푸시를 안했습니다.

2022-10-31 08:51 UTC, Taewoongjung commented
> 혹시 위에서 논의한 내용 중 추가적인 작업이 남았는지 궁금합니다~

코멘트 달린 부분 수정해서 올렸습니다!
* @Service -> @Repository
* repository 의존성 변경 (그림 1 참고)




[그림1]

(변경 전)
![image](https://user-images.githubusercontent.com/70272679/198968638-f6bbb61d-5260-420f-913f-357c1d3cc245.png)


(변경 후)
![image](https://user-images.githubusercontent.com/70272679/198968564-65031991-e512-45e3-976f-05daaefa7d33.png)

2022-10-31 08:56 UTC, Bue-von-hon approved these changes
마이마티스 id 채번방식 조사했어야 했는데 밀렸네요 하하...
잘 수정된것 같습니다~!👍

2022-10-31 12:10 UTC, Taewoongjung commented
@f-lab-Carrey 충돌 해결 후 다시 커밋 했습니다~!

2022-11-01 00:05 UTC, Bue-von-hon commented on src/main/java/app/foodylab/adaptor/infra/mapper/UserMapper.java
> +    void userInsert(User user);
사소한거지만 보통 inserUser, DeleteUser 이렇게 사용하더라구요

2022-11-01 00:15 UTC, Bue-von-hon approved these changes

2022-11-01 00:16 UTC, Bue-von-hon commented
이번에 수정이 꽤 많았는데 잘 수정된것 같네요~!

2022-11-01 09:52 UTC, f-lab-Carrey commented on src/main/java/app/foodylab/adaptor/infra/mybatis/config/DatabaseConfig.java
> +public class DatabaseConfig {
사소하지만 이 클래스의 역할은 MybatisConfig에 더 가까운 느낌이 드네요~

2022-11-01 09:52 UTC, f-lab-Carrey commented on src/main/java/app/foodylab/adaptor/payment/ExternalKakaoPayImpl.java
>          return true;
이 부분은 단순히 true/false의 응답 대신에 처리 결과를 더 명확하게 나타내줘도 좋을 것 같아요~
https://developers.kakao.com/docs/latest/ko/kakaopay/single-payment#request
카카오페이 API를 봐도 엄청나게 많은 데이터를 던져주고 있어요. 
요청 id라던지, 금액, 결제 시간과 같은 여러가지 데이터를 주고 있는데요.

이런 데이터를 기반으로 성공/실패를 구분하거나 http status로 성공/실패를 구분해도 좋을 것 같습니다.
true/false로만 표현하기에는 정보가 좀 적은 것 같네요~

2022-11-01 09:52 UTC, f-lab-Carrey commented on src/main/java/app/foodylab/adaptor/payment/ExternalKakaoPayImpl.java
>          return true;
위의 코드를 간결하게 바꾸면.. 아래와 같이 표현할 수도 있지 않나요?
```java
    @Override
    public boolean processPay(long price) {
        return requestPay() && approvePay();
    }
```

2022-11-01 09:52 UTC, f-lab-Carrey commented on src/main/java/app/foodylab/domain/coupon/PriceCoupon.java
> +        if (Boolean.FALSE.equals(condition)) {
여기도 굳이 이렇게 표현식을 쓸 필요가 있나요? 아래처럼 표현할 수도 있을 것 같아요
```java
if (condition == false) {
  // TODO
}
```

2022-11-01 09:52 UTC, f-lab-Carrey commented on src/main/java/app/foodylab/domain/payment/DiscountPriceCalculateService.java
> +    }
지난번에 쿠폰의 할인방식은 minus도 있는 반면 percentage 할인도 있다고 하셨는데요. 일단은 minus에 대한 할인만 고려하신 걸까요~?

2022-11-01 09:52 UTC, f-lab-Carrey commented on src/main/java/app/foodylab/domain/store/StoreState.java
> +    CLOSED_BUSINESS("CLOSED_BUSINESS");
enum class내의 인자의 이름과 value 값이 같은 경우에는 enum class에서 제공하는 함수를  써볼 수도 있을 것 같네요~

2022-11-01 09:52 UTC, f-lab-Carrey commented on src/test/java/app/foodylab/domain/order/OrderTest.java
> +    }
Stream을 리턴하는 것은 자바를 사용하면서 발생하는 안티 패턴 중 하나입니다.
https://jaehun2841.github.io/2019/02/16/effective-java-item47/

이 글을 참고 부탁드려요~

2022-11-01 10:10 UTC, Taewoongjung commented on src/main/java/app/foodylab/adaptor/infra/mybatis/config/DatabaseConfig.java
> +public class DatabaseConfig {
네 그렇네요!

2022-11-01 10:13 UTC, Bue-von-hon commented on src/main/java/app/foodylab/domain/coupon/PriceCoupon.java
> +        if (Boolean.FALSE.equals(condition)) {
아 이부분은 제가 소나린트가 추천해준 구현으로 변경한 부분이네요
```java 
condition == false 
```
저도 처음에 이렇게 작성했다가 린트에서 추천해줬던걸로 기억하거든요
그래서 지금 재현해보려고 시도하니 또 재현은 안돼네요..?ㅎㅎ
```java
!condition
```
다만 인텔리제이에서는 위처럼 추천해줘서(replace 추천이 뜨더라구요😅) 이런식으로 변경해보면 좋을 것같아요!!

2022-11-01 10:15 UTC, Taewoongjung commented on src/main/java/app/foodylab/adaptor/payment/ExternalKakaoPayImpl.java
>          return true;
사실 이 티켓에서는 Mybatis쪽만 건들였고 Payment, Coupon쪽은 태훈님이 머지한거 현재 remote에 있는거랑 충돌 안나게 패키지 구조만 옮겼습니다..!

Payment, Coupon쪽에 수정할 부분은 따로 티켓을 파겠습니다!

2022-11-01 10:16 UTC, Taewoongjung commented on src/main/java/app/foodylab/domain/payment/DiscountPriceCalculateService.java
> +    }
이 부분은 따로 티켓이 생성되어있어서 작업 예정입니다~!

2022-11-01 11:00 UTC, Taewoongjung commented on src/test/java/app/foodylab/domain/order/OrderTest.java
> +    }
Stream은 iterator를 확장하지 않아서 for-each문을 사용 못하네요. 자바의 신에서 배운 내용인 것 같네요!

Steam과 iterable 알맞게 조합해야 좋은 코드가 나오는데, 동시에 제공할 수 있도록 만들기 위해서는 Collection이나 그 하위 타입을 사용해야합니다.

그런데 Collection으로 하면 원소 수가 30이 넘어가면 Power.of 예외를 던지네요..!

2022-11-01 11:03 UTC, Taewoongjung commented on src/test/java/app/foodylab/domain/order/OrderTest.java
> +    }
그런데 https://junit.org/junit5/docs/5.8.1/api/org.junit.jupiter.params/org/junit/jupiter/params/ParameterizedTest.html 여기를 보면 

![image](https://user-images.githubusercontent.com/70272679/199219078-91662de3-8b74-464a-a2c4-d0b08374d17b.png)

ParameterizedTest를 사용하려면 Stream을 사용해야하나봐요..!

2022-11-01 11:09 UTC, Bue-von-hon commented on src/test/java/app/foodylab/domain/order/OrderTest.java
> +    }
> In this context, a "stream" is anything that JUnit can reliably convert into a Stream, such as Stream, DoubleStream, LongStream, IntStream, Collection, Iterator, Iterable

저는 커맨드 + B를 통해서 해당 어노테이션 소스코드에서 확인했는데요
저기서 말하는 스트림은 자바 스트림 api보다 조금 더 광범위한거라 collection 사용이 가능해 보입니다..!

2022-11-01 11:13 UTC, Taewoongjung commented on src/test/java/app/foodylab/domain/order/OrderTest.java
> +    }
더 깊이 들어가서 MethodSource 메소드를 찾아보니 Stream이 Stream(자바의 API)가 아니라 

![image](https://user-images.githubusercontent.com/70272679/199220699-1d9cc6ab-bb26-481c-94c0-1fbc9496a19f.png)

Stream, Collection, Iterator, Iterable 등을 통칭하고 있었네요!

https://junit.org/junit5/docs/5.8.1/api/org.junit.jupiter.params/org/junit/jupiter/params/provider/MethodSource.html

2022-11-01 15:12 UTC, f-lab-Carrey approved these changes
이상으로 중요한 이슈는 모두 해결된 것으로 보여 Approve 하도록 하겠습니다.
고생 많으셨습니다~!

2022-11-01 15:12 UTC, f-lab-Carrey commented on src/testFixtures/java/app/foodylab/StoreFixture.java
> +        StoreState.valueOf("OPEN"),
여기는 그냥 StoreState.OPEN이 더 좋은 패턴이라고 생각되네요. 굳이 valueOf로 찾을 필요는 없어보입니다.
valueOf 메서드를 사용할 때 주의할 점을 확인해보시면 좋겠습니다

2022-11-01 16:38 UTC, Taewoongjung commented on src/testFixtures/java/app/foodylab/StoreFixture.java
> +        StoreState.valueOf("OPEN"),
1. valueOf(null)이 들어오면 default: 로 가지 않고 NPE가 발생합니다.
2. enum 클래스에 정의되어 있지 않은 값을 valueOf 인자로 넘길 경우 IllegalArgumentException 에러가 발생합니다. 그래서 에러를 따로 잡아줘야 하는 번거러움이 있습니다.

2022-11-01 16:39 UTC, merged